@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":StudentBookParser" as sbp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> sbp ++: parseCommand(commandText)
create ecp
sbp -> ecp
sbp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editStudentDescriptor
ec --> ecp --
ecp --> sbp --: command
sbp --> logic --: command

@enduml
