@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "UserPrefs Storage" #F4F6F6{
Class JsonUserPrefsStorage
}

package "StudentBook Storage" #F4F6F6{
Class JsonStudentBookStorage
Class JsonSerializableStudentBook
Class JsonAdaptedStudent
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" JsonUserPrefsStorage
StorageManager -down-> "1" JsonStudentBookStorage

JsonStudentBookStorage ..> JsonSerializableStudentBook
JsonSerializableStudentBook --> "*" JsonAdaptedStudent
JsonAdaptedStudent --> "*" JsonAdaptedTag

@enduml
