@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedStudentBook" as VersionedStudentBook MODEL_COLOR
end box

[-> Model : undoStudentBook()
activate Model

Model -> VersionedStudentBook : undo()
activate VersionedStudentBook

VersionedStudentBook -> VersionedStudentBook :resetData(ReadOnlyStudentBook)
VersionedStudentBook --> Model :
deactivate VersionedStudentBook

[<-- Model
deactivate Model

@enduml
